---
- name: "Join worker nodes"
  community.docker.docker_swarm:
    state: join
    timeout: 60
    remote_addrs:
      - "{{ groups['manager'][0] }}"
    join_token: "{{ hostvars[groups['manager'][0]]['output']['swarm_facts']['JoinTokens']['Worker'] }}"
