version: '3'
services:
  app:
    # for update:
    # commend following line, uncomment line below that
    image: shinsenter/php:8.0-fpm-apache
    #image: shinsenter/php:8.1-fpm-apache
    env_file:
      - .env
    volumes:
      - /shared/tasktap/app/server.php:/var/www/html/server.php
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    depends_on:
      - database
  frontendproxy:
    image: nginx:1.26-bookworm
    ports:
      - 80:80
    volumes:
      - /shared/tasktap/frontendproxy/:/etc/nginx/conf.d/
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    depends_on:
      - app
  database:
    image: mariadb:lts
    env_file:
      - .env
    volumes:
      - /shared/tasktap/database/:/var/lib/mysql/
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
  phpmyadmin:
    image: phpmyadmin:latest
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
    depends_on:
      - database
