---
- name: "Install basic softwares, tools and dependencies"
  hosts: all
  roles:
    - base

- name: "Join managers to cluster"
  hosts: manager
  roles:
    - managers

- name: "Join workers to cluster"
  hosts: worker
  roles:
    - workers
