---
- name: "Setup NFS server"
  hosts: storage
  roles:
    - storage

- name: "Install basic softwares, tools and dependencies"
  hosts: manager, worker
  roles:
    - base

- name: "Join managers to cluster"
  hosts: manager
  roles:
    - managers

- name: "Join workers to cluster"
  hosts: worker
  roles:
    - workers

- name: "Deploy stacks"
  hosts: manager[0]
  roles:
    - deploy

- name: "Cleanup"
  hosts: manager, worker
  tasks:
    - name: "Prune containers, networks, volumes"
      community.docker.docker_prune:
        containers: true
        networks: true
        volumes: true
