-- create the databases
CREATE DATABASE IF NOT EXISTS $DB_NAME;

-- create the users for each database
CREATE USER $DB_USER@'%' IDENTIFIED BY $DB_PASS;
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON $DB_USER.* TO $DB_USER@'%';

FLUSH PRIVILEGES;