---
- name: "Setup tasktap stack"
  ansible.builtin.include_tasks: "tasktap.yml"

- name: "Deploy stacks"
  community.docker.docker_stack:
    name: tasktap
    state: present
    compose:
      - "/shared/{{ item }}"
  loop:
    - tasktap/tasktap-compose.yaml
